<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-05">
<meta name="description" content="Second-generation rocket telemetry: a Raspberry Pi 5 ground station that receives LoRa natively in Python, a versioned packet contract shared by every node, 10 Hz flight-rate telemetry with onboard velocity and G envelopes, a fail-closed LED panel beside a status OLED, and a flight archive that publishes itself. Two Katana Jr flights recorded at under 1 % packet loss.">

<title>LoRa RadioRocket V2 – Francisco Velez | Data Science Portfolio</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3e9b1289f5f353c49b617ce48ad2bc38.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Francisco Velez | Data Science Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#what-changed-from-v1" id="toc-what-changed-from-v1" class="nav-link" data-scroll-target="#what-changed-from-v1">What changed from V1</a></li>
  <li><a href="#system-architecture" id="toc-system-architecture" class="nav-link" data-scroll-target="#system-architecture">System architecture</a></li>
  <li><a href="#the-packet-contract" id="toc-the-packet-contract" class="nav-link" data-scroll-target="#the-packet-contract">The packet contract</a></li>
  <li><a href="#the-sled-sample-fast-transmit-slow" id="toc-the-sled-sample-fast-transmit-slow" class="nav-link" data-scroll-target="#the-sled-sample-fast-transmit-slow">The sled: sample fast, transmit slow</a>
  <ul class="collapse">
  <li><a href="#confirmed-apogee-and-the-harness-that-measured-it" id="toc-confirmed-apogee-and-the-harness-that-measured-it" class="nav-link" data-scroll-target="#confirmed-apogee-and-the-harness-that-measured-it">Confirmed apogee, and the harness that measured it</a></li>
  <li><a href="#why-10-hz-needed-a-bandwidth-change" id="toc-why-10-hz-needed-a-bandwidth-change" class="nav-link" data-scroll-target="#why-10-hz-needed-a-bandwidth-change">Why 10 Hz needed a bandwidth change</a></li>
  <li><a href="#what-rides-on-the-wire-now" id="toc-what-rides-on-the-wire-now" class="nav-link" data-scroll-target="#what-rides-on-the-wire-now">What rides on the wire now</a></li>
  </ul></li>
  <li><a href="#learning-link-budgets-and-what-they-decided" id="toc-learning-link-budgets-and-what-they-decided" class="nav-link" data-scroll-target="#learning-link-budgets-and-what-they-decided">Learning link budgets, and what they decided</a>
  <ul class="collapse">
  <li><a href="#the-arithmetic" id="toc-the-arithmetic" class="nav-link" data-scroll-target="#the-arithmetic">The arithmetic</a></li>
  <li><a href="#the-antenna-i-did-not-know-was-missing" id="toc-the-antenna-i-did-not-know-was-missing" class="nav-link" data-scroll-target="#the-antenna-i-did-not-know-was-missing">The antenna I did not know was missing</a></li>
  <li><a href="#what-good-adxl375-data-needed" id="toc-what-good-adxl375-data-needed" class="nav-link" data-scroll-target="#what-good-adxl375-data-needed">What good ADXL375 data needed</a></li>
  <li><a href="#why-attitude-pushed-me-to-a-teensy" id="toc-why-attitude-pushed-me-to-a-teensy" class="nav-link" data-scroll-target="#why-attitude-pushed-me-to-a-teensy">Why attitude pushed me to a Teensy</a></li>
  </ul></li>
  <li><a href="#the-ground-station" id="toc-the-ground-station" class="nav-link" data-scroll-target="#the-ground-station">The ground station</a>
  <ul class="collapse">
  <li><a href="#native-receive-no-rx-firmware" id="toc-native-receive-no-rx-firmware" class="nav-link" data-scroll-target="#native-receive-no-rx-firmware">Native receive, no RX firmware</a></li>
  <li><a href="#the-clock-problem" id="toc-the-clock-problem" class="nav-link" data-scroll-target="#the-clock-problem">The clock problem</a></li>
  <li><a href="#two-surfaces-not-peers" id="toc-two-surfaces-not-peers" class="nav-link" data-scroll-target="#two-surfaces-not-peers">Two surfaces, not peers</a></li>
  <li><a href="#the-oled" id="toc-the-oled" class="nav-link" data-scroll-target="#the-oled">The OLED</a></li>
  <li><a href="#dashboard-and-power" id="toc-dashboard-and-power" class="nav-link" data-scroll-target="#dashboard-and-power">Dashboard and power</a></li>
  </ul></li>
  <li><a href="#from-session-log-to-web-page" id="toc-from-session-log-to-web-page" class="nav-link" data-scroll-target="#from-session-log-to-web-page">From session log to web page</a></li>
  <li><a href="#flight-day-2026-08-25" id="toc-flight-day-2026-08-25" class="nav-link" data-scroll-target="#flight-day-2026-08-25">Flight day 2026-08-25</a></li>
  <li><a href="#what-i-learned" id="toc-what-i-learned" class="nav-link" data-scroll-target="#what-i-learned">What I learned</a></li>
  <li><a href="#whats-next" id="toc-whats-next" class="nav-link" data-scroll-target="#whats-next">What’s next</a></li>
  <li><a href="#links" id="toc-links" class="nav-link" data-scroll-target="#links">Links</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">LoRa RadioRocket V2</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">IoT</div>
    <div class="quarto-category">telemetry</div>
    <div class="quarto-category">LoRa</div>
    <div class="quarto-category">hardware</div>
    <div class="quarto-category">amateur radio</div>
    <div class="quarto-category">Raspberry Pi</div>
    <div class="quarto-category">Python</div>
    <div class="quarto-category">embedded</div>
  </div>
  </div>

<div>
  <div class="description">
    Second-generation rocket telemetry: a Raspberry Pi 5 ground station that receives LoRa natively in Python, a versioned packet contract shared by every node, 10 Hz flight-rate telemetry with onboard velocity and G envelopes, a fail-closed LED panel beside a status OLED, and a flight archive that publishes itself. Two Katana Jr flights recorded at under 1 % packet loss.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 5, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p><a href="../projects/lora-radiorocket.html">Version 1</a> proved that a Feather M0 in a rocket could stream altitude and G-force to a LePotato on the ground at 1 Hz. It worked on its first flight, and it also taught me what a link is not: it is not a record. The V1 string was unversioned, a second receiver could not be added without copying code, the ground side depended on Node-RED flows I could not test, and a whole flight was about twenty data points.</p>
<p>V2 kept the sled and rebuilt everything around it. The ground station is now a Raspberry Pi 5 that receives LoRa <strong>natively</strong> through a driver I wrote in Python, so there is no RX firmware at all. The packet format is a written, versioned contract that a C encoder on the sled and a Python decoder on the ground both test against. The sled samples at 20 Hz and transmits at 10 Hz in flight. Every flight lands in an append-only session log, is derived into a permalinked record, and appears on the <a href="../projects/lora-flights.html">flight archive</a> the same evening. A separate <a href="../projects/apogee-handheld.html">kids’ handheld</a> listens to the same broadcast.</p>
<p>This page is the V2 write-up. The V1 page and the flight archive stay as they are.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Status, 2026-09-05
</div>
</div>
<div class="callout-body-container callout-body">
<p>Flown and recording. Two Katana Jr flights on 2026-08-25 produced the first real 10 Hz flight records (859 ft and 749 ft AGL, 0.31 % and 0.54 % packet loss). The handheld is built and family-tested. Still ahead: a Teensy 4.1 sled respin with onboard attitude fusion and an SD flight recorder, the deployable lander payload, and a launch-day trial of the handheld game.</p>
</div>
</div>
<p>📡 <strong><a href="../projects/lora-flights.html">Flight archive →</a></strong> — every record, with AGL altitude, link quality, and full 10 Hz traces.</p>
</section>
<section id="what-changed-from-v1" class="level2">
<h2 class="anchored" data-anchor-id="what-changed-from-v1">What changed from V1</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>V1 (2025)</th>
<th>V2 (2026)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ground computer</td>
<td>Libre LePotato + a second Feather M0 as RX</td>
<td>Raspberry Pi 5 (8 GB), radio on the Pi’s own SPI bus</td>
</tr>
<tr class="even">
<td>Receiver code</td>
<td>Arduino RX firmware, serial to Node-RED</td>
<td>Python SX127x driver over <code>spidev</code> + <code>lgpio</code>, host-tested against a fake SPI</td>
</tr>
<tr class="odd">
<td>Packet format</td>
<td>Ad hoc string with emoji and a space-bearing battery status</td>
<td>Versioned <code>KEY:VALUE</code> ASCII contract (ADR 0001), additive tags, tolerant decoders</td>
</tr>
<tr class="even">
<td>Telemetry rate</td>
<td>1 Hz, sampled and transmitted in the same loop</td>
<td>20 Hz sampling; 1 Hz on the pad, 10 Hz in flight (ADR 0005)</td>
</tr>
<tr class="odd">
<td>Radio</td>
<td>434 MHz, BW 125 kHz, 23 dBm</td>
<td>434 MHz, SF7 / BW 500 kHz / CR 4:5, 17 dBm</td>
</tr>
<tr class="even">
<td>Fields</td>
<td>ALT, Max, G, Pg, T, Batt, state</td>
<td>Same, plus SEQ, MET, onboard <code>Vel</code>, G envelope <code>Gmx</code>/<code>Gmn</code>, spin envelope <code>Wmx</code>, 9-DoF pad frames, <code>CALL</code> beacons</td>
</tr>
<tr class="odd">
<td>Flight record</td>
<td>Whatever the dashboard showed</td>
<td>Append-only JSONL session log, derived flights index, published CSV per flight</td>
</tr>
<tr class="even">
<td>Status at the pad</td>
<td>Laptop dashboard</td>
<td>Six-LED panel (own process, fail-closed), 128×64 OLED, phone dashboard over hotspot</td>
</tr>
<tr class="odd">
<td>Clock</td>
<td>Whatever the SBC booted with</td>
<td>PiSugar RTC restore at boot and a fail-closed clock gate before any session opens</td>
</tr>
<tr class="even">
<td>Testing</td>
<td>Flash and see</td>
<td>Host-side TDD for every piece of logic: 88 native firmware tests, 400 ground tests, 83 handheld tests</td>
</tr>
<tr class="odd">
<td>Other receivers</td>
<td>None</td>
<td>Kids’ handheld on a Pi Zero 2 W, importing the ground decoder unchanged</td>
</tr>
</tbody>
</table>
<p>The APRS digipeater side of the V1 box (RTL-SDR + Direwolf) carried over into the V2 enclosure, but it is not part of this telemetry system and I have left it out of this write-up.</p>
</section>
<section id="system-architecture" class="level2">
<h2 class="anchored" data-anchor-id="system-architecture">System architecture</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  subgraph rocket["Rocket sled — SRC:1"]
    FW["Feather M0 + RFM96&lt;br/&gt;BMP390 · ADXL375 · 9-DoF&lt;br/&gt;20 Hz sample · 1/10 Hz TX"]
  end
  FW -- "434 MHz LoRa&lt;br/&gt;V:1 KEY:VALUE frames" --&gt; RX
  FW -. broadcast .-&gt; HH["Kids' handheld&lt;br/&gt;Pi Zero 2 W + bonnet"]
  subgraph gs["Ground station — apogee-gs (Pi 5)"]
    RX["sx127x driver&lt;br/&gt;spidev + lgpio"] --&gt; ING["apogee-ingest&lt;br/&gt;decode · link stats · flight detect"]
    ING --&gt; LOG["session JSONL&lt;br/&gt;append-only"]
    ING --&gt; DASH["Flask dashboard&lt;br/&gt;phone hotspot"]
    ING --&gt; OLED["128×64 OLED&lt;br/&gt;what the flight is doing"]
    ING -- heartbeat --&gt; PANEL["apogee-panel&lt;br/&gt;6 LEDs · is the system working"]
  end
  LOG --&gt; FLT["flights CLI&lt;br/&gt;segment · derive AGL · export"]
  FLT --&gt; WEB["flights.json + CSV&lt;br/&gt;velezf.github.io"]
</pre>
</div>
<p></p><figcaption> One transmitter, many listeners. The sled is the only C++ in the project; everything on the ground is Python.</figcaption> </figure><p></p>
</div>
</div>
</div>
<p>The shape that matters is on the right: one process owns the radio and fans decoded observations out to consumers, and time is injected into that observation once. No consumer reads a clock. Three files are written by three different writers, never shared: the session log by the service, an ops journal by the CLI, and the flights index by pure derivation from the other two. Rebuilding the index from the same inputs produces byte-identical output, which is what lets me trust a number on the archive page months later.</p>
</section>
<section id="the-packet-contract" class="level2">
<h2 class="anchored" data-anchor-id="the-packet-contract">The packet contract</h2>
<p>The single most useful decision in V2 was writing the wire format down before touching either end. <a href="https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/adr/0001-packet-format-v1.md">ADR 0001</a> defines a v1 packet as space-delimited ASCII tokens, each a <code>KEY:VALUE</code> pair, the first always <code>V:1</code>:</p>
<pre><code>V:1 SYS:7 SRC:1 SEQ:42 St:1 ALT:1234ft Max:5678ft G:2.3 Pg:9.1 T:21.5C Batt:3.92V MET:12</code></pre>
<p>That exact string is a golden vector. The C encoder on the sled and the Python decoder on the ground each carry a unit test that asserts against it, so the two implementations can only drift by failing a test. The rules that make it evolvable:</p>
<ul>
<li><strong>Keyed, not positional.</strong> A decoder keys on tag names, ignores tags it does not know, and tolerates absent ones. A missing tag is valid, not an error.</li>
<li><strong>Additive changes do not bump the version.</strong> <code>Vel</code>, <code>Gmx</code>, <code>Gmn</code>, <code>Wmx</code> and the 9-DoF pad-frame channels were all added within v1 without touching any deployed receiver.</li>
<li><strong>Only breaking changes bump <code>V</code>.</strong> Renaming a tag, changing its units, or changing the grammar. A decoder that sees an unknown version must reject the packet and count it, never best-effort parse.</li>
<li><strong>Addressing rides in the payload.</strong> <code>SYS</code> is the network, <code>SRC</code> the vehicle (1 sled, 2 lander). Because they are in the string and not in a radio header, the contract is transport-agnostic.</li>
<li><strong>Integrity is the LoRa PHY CRC.</strong> No application checksum in v1; the driver drops and counts CRC failures before the decoder ever sees them.</li>
</ul>
<p>ASCII costs airtime. A 139-byte frame carries about fifteen numbers that would pack into thirty bytes, a tax of roughly four times. I kept it deliberately: every defect I have found in this project so far was found by reading a session log or a serial console with my eyes, and a binary format would take that away. It is recorded as the next lever if I ever need more than about 17 packets per second, since bandwidth is exhausted at BW 500.</p>
</section>
<section id="the-sled-sample-fast-transmit-slow" class="level2">
<h2 class="anchored" data-anchor-id="the-sled-sample-fast-transmit-slow">The sled: sample fast, transmit slow</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/v2-sled-boards.jpg" class="img-fluid figure-img"></p>
<figcaption>The V2 sled board set before assembly: Feather M0 RFM96 with the quarter-wave wire antenna, BMP390 barometer, ADXL375 high-G accelerometer (±200 g), LSM6DSOX + LIS3MDL 9-DoF, and a 350 mAh LiPo.</figcaption>
</figure>
</div>
<p>The V1 firmware sampled and transmitted in the same loop, gated by a one-second delay. The consequence showed up on the first V2 bench test: a hand-swung sled produced a 2.2 g jerk that fell between samples and never tripped launch detection. The detectors were only as fast as the radio.</p>
<p>V2 splits them. The loop samples the barometer and accelerometers on a 50 ms tick and transmits on a separate schedule. A failed barometer read now skips that one sample instead of returning from the whole loop and costing a packet. The firmware measures and prints its own achieved sample rate every five seconds, because the BMP390’s throughput at a given oversampling is a property to measure, not to assume. It first came in at 17 Hz; the missing time turned out to be the radio library busy-waiting on the previous transmission, not the barometer, and making the transmit non-blocking brought it to 20 Hz.</p>
<section id="confirmed-apogee-and-the-harness-that-measured-it" class="level3">
<h3 class="anchored" data-anchor-id="confirmed-apogee-and-the-harness-that-measured-it">Confirmed apogee, and the harness that measured it</h3>
<p>The V1 apogee detector declared apogee on the first sample that was not higher than the running max, and latched. One noisy sample during boost could set the descent state for the rest of the flight, and every subsequent packet would carry a wrong flight state that no ground-side processing could recover, because the truth was never transmitted.</p>
<p>V2’s detector requires 20 ft of hysteresis below the running max <strong>and</strong> 300 ms of continuous dwell, with both constants in time rather than sample counts so a slower achieved rate degrades precision instead of silently redefining the criterion. To size it I built a synthetic flight profile with an analytic ground truth and a harness that runs any detector at any sample rate. It immediately corrected a threefold arithmetic error in my own plan: confirmed-apogee latency costs 77.9 ft of altitude at 1 Hz and 33.8 ft at 20 Hz, not the 257 and 27 I had estimated, and most of the benefit is already won by 5 Hz.</p>
</section>
<section id="why-10-hz-needed-a-bandwidth-change" class="level3">
<h3 class="anchored" data-anchor-id="why-10-hz-needed-a-bandwidth-change">Why 10 Hz needed a bandwidth change</h3>
<p>A whole flight of this class is about twenty seconds. At 1 Hz that is twenty points, enough to say a flight happened, not enough to plot it. The target that drove <a href="https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/adr/0005-telemetry-rate-and-rf-configuration.md">ADR 0005</a> was an OpenRocket-style plot: altitude, vertical velocity and acceleration against time, with event markers.</p>
<p>Three LoRa parameters set throughput. The coding rate was already minimal. SF6 would have required implicit-header fixed-length packets, which fights the variable-length tolerant format at the mechanism level. That left bandwidth:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Bandwidth</th>
<th>Time on air, 139 B</th>
<th>Duty at 10 Hz</th>
<th>Sensitivity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>125 kHz (V1)</td>
<td>235.8 ms</td>
<td>236 %, impossible</td>
<td>−123 dBm</td>
</tr>
<tr class="even">
<td>250 kHz</td>
<td>117.9 ms</td>
<td>118 %, impossible</td>
<td>−120 dBm</td>
</tr>
<tr class="odd">
<td><strong>500 kHz</strong></td>
<td><strong>58.9 ms</strong></td>
<td><strong>58.9 %</strong></td>
<td><strong>−117 dBm</strong></td>
</tr>
</tbody>
</table>
<p>At the V1 bandwidth 10 Hz was not expensive, it was unreachable. Going to 500 kHz costs 6 dB of sensitivity, and whether the link could afford that is the question the next section is about. TX power dropped from 23 to 17 dBm as part of the same decision, because at 59 % duty the transmitter is keyed more than half the time and heat becomes the binding constraint.</p>
<p>Transmit rate is state-dependent: 1 Hz on the pad, 10 Hz from confirmed launch for a 300 s window bounded by mission elapsed time, then back to a 1 Hz recovery beacon. The window is bounded by MET because nothing else bounds it; without a landed state code, “fast while airborne” would key the transmitter until the battery died in the grass.</p>
</section>
<section id="what-rides-on-the-wire-now" class="level3">
<h3 class="anchored" data-anchor-id="what-rides-on-the-wire-now">What rides on the wire now</h3>
<p>Three fields were added within v1 for the plot, and the reasoning behind each is in the link-budget section below: <code>Vel</code>, vertical velocity computed on board at the sample rate; <code>Gmx</code> and <code>Gmn</code>, the acceleration envelope across each transmit window; and <code>Wmx</code>, the same window mechanism over gyro magnitude so spin cannot alias however fast the airframe rolls.</p>
<p>Frame shape follows flight state: pad frames carry the raw 9-DoF channels at 1 Hz as a calibration dataset, flight frames carry the envelopes. Every transmitter also beacons its callsign (KC3ZTQ) at start, at least every 9.5 minutes, and at shutdown, per Part 97. Beacons are counted separately and never participate in flight accounting: a landed rocket beaconing every minute must not hold a flight open.</p>
</section>
</section>
<section id="learning-link-budgets-and-what-they-decided" class="level2">
<h2 class="anchored" data-anchor-id="learning-link-budgets-and-what-they-decided">Learning link budgets, and what they decided</h2>
<p>I came into V2 without ever having done a link budget. V1 worked, so I had never needed one. V2 forced the question three separate times, and each time the arithmetic ended up choosing a design I would not have picked by intuition. This section is the elementary version, written the way I worked it out.</p>
<section id="the-arithmetic" class="level3">
<h3 class="anchored" data-anchor-id="the-arithmetic">The arithmetic</h3>
<p>A link budget is bookkeeping in decibels. Start with what the transmitter puts out, subtract what the path takes away, and compare what is left against the weakest signal the receiver can still decode. Free-space path loss for a distance <em>d</em> in kilometres at frequency <em>f</em> in megahertz is</p>
<p><span class="math display">\[\text{FSPL} = 32.44 + 20\log_{10}(f) + 20\log_{10}(d)\]</span></p>
<p>For 434 MHz and a worst-case slant range of 1.5 km, which is generous for the flights this system flies:</p>
<pre><code>FSPL   = 32.44 + 20·log10(434) + 20·log10(1.5) = 88.7 dB
RX     = 17 dBm − 88.7 dB                        = −71.7 dBm   (0 dBi antennas both ends)
margin = −71.7 − (−117)                          = 45.3 dB</code></pre>
<p>Subtract 2 to 3 dB for connectors and cable and call it 42 dB. The number that gave me confidence was not the clear-air figure but what it leaves for fading: a tumbling airframe sweeps its antenna pattern through deep nulls, and 20 to 30 dB fades are ordinary. A 42 dB margin absorbs a 30 dB fade with room left.</p>
<p>The −117 dBm in that sum is the receiver’s sensitivity, and this is where bandwidth entered. LoRa sensitivity gets 3 dB worse every time bandwidth doubles, because the receiver is integrating noise over twice the spectrum. 125 kHz gives −123 dBm, 500 kHz gives −117 dBm. So the 10 Hz decision was really the sentence “I am spending 6 dB of my 48 dB on time”, and the budget said I could.</p>
<p>Two other pieces of the picture were new to me. Duty cycle is not a regulatory limit under Part 97, so it shows up as a thermal constraint on the transmitter, which is why TX power dropped to 17 dBm as part of the same decision. And the 500 kHz channel centred on 434.0 MHz occupies 433.75 to 434.25 MHz, inside the 70 cm amateur allocation, where amateur is secondary and the band is shared with a great deal of 433 MHz ISM traffic. That is a noise-floor consideration, not a legality one, and it is the argument for keeping margin rather than spending all of it.</p>
</section>
<section id="the-antenna-i-did-not-know-was-missing" class="level3">
<h3 class="anchored" data-anchor-id="the-antenna-i-did-not-know-was-missing">The antenna I did not know was missing</h3>
<p>The budget is a design assumption until something measures it, and the first measurement said the design was fiction. Bench RSSI at a few feet had been sitting around −80 dBm when the recorded bench band for that geometry was −38 to −14 dBm. Somewhere between 42 and 66 dB of the budget was simply not there. The receive chain had a re-soldered u.FL connector and a damaged bulkhead pigtail, and until they were fixed every weak-signal symptom was the connector until proven otherwise. After the repair, close-range RSSI came back to −40 ±1 dBm with zero loss and a standard deviation of 0.38 dB over 45 packets, 2 dB shy of the bench band and attributed to the insertion loss of the new connector chain.</p>
<p>Only a flight could measure the rest. On 2026-08-25 the worst in-flight RSSI was −101 dBm at about 860 ft, against −117 dBm sensitivity: 16 dB of real margin at the worst moment of the flight, fades included, at less than a fifth of the range the budget was sized for. That number replaced the design assumption in the ADR, and the packet loss it came with was 0.31 %.</p>
</section>
<section id="what-good-adxl375-data-needed" class="level3">
<h3 class="anchored" data-anchor-id="what-good-adxl375-data-needed">What good ADXL375 data needed</h3>
<p>The high-G accelerometer is the sled’s launch detector and its only view of boost, and V1 was wasting it. The first V2 bench test made that concrete: a hand swing produced a 2.2 g jerk that fell between two 1 Hz samples and never tripped the 3 g launch threshold. The sensor saw it; the loop did not.</p>
<p>The link budget decided how this got fixed, because every option cost bytes on the wire, and bytes are airtime, and airtime is the thing the budget had just priced.</p>
<ul>
<li><strong>Sample fast, transmit slow.</strong> Decoupling the sample tick from the transmit tick cost nothing in airtime, so it came first. The ADXL375 is now read every 50 ms regardless of when the radio next keys up.</li>
<li><strong>Send the envelope, not the sample.</strong> Even at 10 Hz, an instantaneous reading misses a spike that lasts 20 ms, and the plotted amplitude would depend on which phase of the boost the sample happened to land in. The fix is to compute the minimum and maximum acceleration magnitude across each transmit window on board and send both, reset only when a frame actually goes to air, so a skipped transmission widens the window rather than losing the spike. That makes spike amplitudes exact at any transmit rate, which decouples the accelerometer’s correctness from the rate decision entirely.</li>
<li><strong>Budget the bytes.</strong> Those two tags plus onboard velocity took the worst-case frame from 109 to 141 bytes, which is why the airtime table above is computed at 139 and why the decision is 58.9 % duty rather than 45 %. An earlier increment that tried to send the three raw axes found the firmware’s message buffer was 128 bytes against a 143-byte worst case, and that truncation was silent: a frame cut short decoded as a valid packet with a plausible wrong value. Both the buffer and the encoder were fixed so overflow is loud, and the per-axis tags were parked because the envelope answers the question they were asked for.</li>
<li><strong>What not to send.</strong> Splitting slow-changing tags across alternate packets would have saved about 13 % of airtime and made “absent” indistinguishable from “unchanged” for every consumer. The budget had already bought enough headroom that the complexity had nothing to purchase.</li>
</ul>
<p>The principle that fell out, and that the next subsection extends, is to derive where the data is dense and transmit the derivative. Velocity is computed on board at 20 Hz because differentiating 10 Hz altitude on the ground amplifies the barometer’s quantisation into noise. The G envelope is computed on board for the same reason.</p>
</section>
<section id="why-attitude-pushed-me-to-a-teensy" class="level3">
<h3 class="anchored" data-anchor-id="why-attitude-pushed-me-to-a-teensy">Why attitude pushed me to a Teensy</h3>
<p>The 9-DoF sensors are on the sled, and the obvious plan was to stream their raw gyro and accelerometer values and fuse them into an attitude on the Pi. The link budget closed that door in one afternoon of arithmetic.</p>
<p>Fusion needs raw samples at 50 Hz or more. At SF7 and 500 kHz, ASCII raw frames at 50 Hz come to 352 % duty. A minimal 20-byte binary frame per sample is 77 %, over the 65 % line I had set for thermal reasons. A realistic 34-byte binary frame is 103 %, over the radio’s ceiling itself. Batching five samples into a 10 Hz binary packet does fit, at about 32 % duty, so duty alone does not close the question. Two other legs do. Batching requires a binary v2 format, the largest contract change the system could make. And the load-bearing one: attitude is an integration, and integrating over a lossy radio link means every tumble fade punches a hole in the input and the solution diverges during exactly the dynamics it exists to capture. Onboard integration has a loss-free input by construction. No transport fixes that.</p>
<p>So attitude is computed on board or it does not exist live. That put the question to the Feather M0, a 48 MHz Cortex-M0+ with no floating-point unit: could it run a Mahony filter at 100 Hz in software floats alongside everything it already does? I never had to measure it. The Teensy 4.1 was already on hand, and its 600 MHz Cortex-M7 with an FPU makes the question moot, while its built-in microSD slot becomes the full-rate flight recorder for the one product the radio can never carry, spin spectra from the IMU FIFO at 833 Hz. The plan runs the core down to 150 MHz, which roughly quarters the MCU’s draw; in flight the radio at 17 dBm and 59 % duty dominates the power budget anyway, so the clock is a pad-endurance knob rather than a flight one.</p>
<p>The port cost was measured before deciding. Every firmware unit in <code>lib/</code> has zero board includes, so the detectors, encoder, conversions and the profile harness move without edits along with their native tests. The entire port surface is the one hardware glue file, and the two things that do not carry over are the Feather’s hardwired radio pins and its battery-sense divider, which is board wiring and would silently produce plausible wrong volts if forgotten.</p>
<p>Sequencing was firm: the 10 Hz build flew on the Feather first. Stacking an unflown MCU port on an unflown RF rewrite would have meant failures that could not be attributed to either.</p>
</section>
</section>
<section id="the-ground-station" class="level2">
<h2 class="anchored" data-anchor-id="the-ground-station">The ground station</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/v2-gs-interior.jpg" class="img-fluid figure-img"></p>
<figcaption>Inside the V2 box, lid off. The Pi 5 sits under a proto-board carrier; the RFM96W breakout on its SPI bus feeds the left bulkhead SMA through a u.FL pigtail. The RTL-SDR on the right serves the APRS digipeater. The 1.3” OLED is taped in for the bench.</figcaption>
</figure>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Raspberry Pi 5 (8 GB), Pi OS 64-bit Trixie</td>
<td>Runs the ingest service, dashboard, OLED and panel supervisor</td>
</tr>
<tr class="even">
<td>RFM96W breakout on SPI0, CE1</td>
<td>Native LoRa receive; DIO0 deliberately unwired, the driver polls</td>
</tr>
<tr class="odd">
<td>Adafruit 1.3” SSD1306 128×64 OLED on I²C</td>
<td>Flight display</td>
</tr>
<tr class="even">
<td>Six front-panel LEDs on GPIO</td>
<td>System-health panel, driven by its own process</td>
</tr>
<tr class="odd">
<td>PiSugar 3 Plus UPS, 5000 mAh</td>
<td>Battery, real-time clock, graceful shutdown, wake-on-charge</td>
</tr>
<tr class="even">
<td>12 V → 5 V buck into the PiSugar charge port</td>
<td>Field power from a vehicle or pack</td>
</tr>
<tr class="odd">
<td>Blue metal project box, run lid-off</td>
<td>Airflow over passive heatsinks and no shielding of the Pi’s Wi-Fi</td>
</tr>
</tbody>
</table>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/v2-gs-pisugar.jpg" class="img-fluid figure-img"></p>
<figcaption>The PiSugar 3 Plus mounts under the Pi on pogo pins. Both the Pi 5 and the Zero needed a bit of solder on the pogo pads before the I²C interface showed up.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/v2-gs-front-panel.jpg" class="img-fluid figure-img"></p>
<figcaption>Front panel: the SCE-to-AUX switch carried over from V1, and the six-LED row. Blue, blue, red, green, green, green, left to right.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<section id="native-receive-no-rx-firmware" class="level3">
<h3 class="anchored" data-anchor-id="native-receive-no-rx-firmware">Native receive, no RX firmware</h3>
<p>The plan called for Adafruit’s <code>rfm9x</code> library on Blinka. On the Pi 5 that fell apart: <code>RPi.GPIO</code> maps BCM283x registers directly and does not run on the Pi 5’s RP1, and Blinka’s build pulled in dependencies that would not compile in an isolated venv. Rather than shim it, I wrote a small SX127x driver over raw <code>spidev</code> and <code>lgpio</code> (<a href="https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/adr/0002-ground-rx-driver-spidev.md">ADR 0002</a>). It mirrors the sled’s RadioHead modem configuration, enforces the CRC, strips the four-byte RadioHead header, and hands validated payload bytes to the decoder. The SPI transport is injected, so register and frame logic run on my Mac against a fake SPI with no hardware.</p>
<p>The whole ground stack ended up Blinka-free: OLED via <code>luma.oled</code>, LEDs via <code>lgpio</code>, radio via <code>spidev</code>. The radio is receive-only by construction, not by convention: the driver defines only sleep, standby and continuous-receive modes, and no transmit or power-amplifier register is ever written. That is what makes it safe to power the box without an antenna while a pigtail is on order. The sled has the opposite rule and never runs without one.</p>
</section>
<section id="the-clock-problem" class="level3">
<h3 class="anchored" data-anchor-id="the-clock-problem">The clock problem</h3>
<p>Every session and record is timestamped from the system clock at the moment the radio owner sees the frame. On 2026-07-13 the box booted with a mis-dated session, and the chain was instructive. The Pi 5’s onboard RTC has no coin cell, so the kernel came up in 1970. The time-sync daemon then advanced the clock to its saved floor, the last shutdown time. Nothing had read the PiSugar’s battery-backed RTC, which was correct. My old gate checked that the year was at least 2024, the stale floor passed it, and a session opened four days in the past. Wi-Fi fixed it that time; offline at a launch site it would have been a silently corrupt record.</p>
<p><a href="https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/adr/0003-rtc-boot-restore-clock-gate.md">ADR 0003</a> fixed it in two coupled parts. A oneshot unit reads the PiSugar RTC before ingest starts and sets the system clock only when it is bogus or grossly behind, never stepping backward, and drops a trust marker. The ingest service then refuses to start unless the clock is NTP-synced or that marker exists. A plausible year alone no longer passes. For the case of a dead RTC and no network there is an operator escape hatch: set the clock from a phone and attest it. Silence and duration inside the service use monotonic deltas, so a later clock step cannot distort a flight’s length. The whole thing was verified on a cold boot with Wi-Fi off.</p>
</section>
<section id="two-surfaces-not-peers" class="level3">
<h3 class="anchored" data-anchor-id="two-surfaces-not-peers">Two surfaces, not peers</h3>
<p>The box has two displays and they answer different questions. The LED panel answers “is the system working”. The OLED answers “what is the flight doing”. The distinction is structural. The panel supervisor is its own process that reads a heartbeat file the ingest service publishes; when ingest dies the heartbeat goes stale and the supervisor drives the red LED, fail-closed. The OLED’s render thread lives inside ingest, so when that process dies the display freezes showing plausible content and cannot report its own death.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Position</th>
<th>Colour</th>
<th>Name</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>blue</td>
<td>RF</td>
<td>RF trouble: foreign traffic or climbing CRC errors <em>(designed, not yet wired end-to-end)</em></td>
</tr>
<tr class="even">
<td>2</td>
<td>blue</td>
<td>CLOCK</td>
<td>Clock provenance: solid when restored from the RTC</td>
</tr>
<tr class="odd">
<td>3</td>
<td>red</td>
<td>NOT RECORDING</td>
<td>Solid when ingest is down or the clock gate refused; fast blink at low battery; slow pulse while shutting down</td>
</tr>
<tr class="even">
<td>4</td>
<td>green</td>
<td>FLIGHT</td>
<td>Solid while a flight is open</td>
</tr>
<tr class="odd">
<td>5</td>
<td>green</td>
<td>RX</td>
<td>Fast blink on fresh packets</td>
</tr>
<tr class="even">
<td>6</td>
<td>green</td>
<td>ALIVE</td>
<td>1 Hz heartbeat, never solid, so a frozen supervisor shows as a stuck LED rather than a healthy one</td>
</tr>
</tbody>
</table>
<p>The operator rule that follows: when the two surfaces disagree, believe the LEDs. A dark RX LED under a plausible altitude on the OLED means ingest is dead and the screen is showing the past.</p>
<p>Mapping those six positions was its own lesson. The harness is cross-wired, so physical order is not GPIO order. My first map, taken from watching a lamp sweep, was reversed in every position and stood wrong for three weeks. Lighting one LED at a time and counting its position was the only reliable method, and the map now lives as data in one Python module where a host test enforces that the GPIO table, the colour table and the lamp-test order agree.</p>
</section>
<section id="the-oled" class="level3">
<h3 class="anchored" data-anchor-id="the-oled">The OLED</h3>
<p>The V1 box had no display. The first V2 OLED rendered straight off each decoded packet, which meant a quiet pad drew nothing and looked exactly like a dead box. The redesign moved rendering onto its own thread off a view-model snapshot, gave the pad an idle page, and put a spinning liveness glyph in the corner that proves the render thread is turning. The hero digits are hand-drawn 28-pixel bitmaps approved outdoors on the real panel before golden-image tests froze them, because a golden preserves whatever it was generated from, mistakes included.</p>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/gs-oled-idle.png" class="img-fluid figure-img"></p>
<figcaption>Idle: no sled heard yet. Clock provenance shows here and only here, where the operator can cross-check it against the CLOCK LED.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/gs-oled-pad.png" class="img-fluid figure-img"></p>
<figcaption>Pad: the sled is up, baseline locking, altitude zeroed AGL.</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/gs-oled-live.png" class="img-fluid figure-img"></p>
<figcaption>Live ascent. Callsign in the header because Part 97 gives it a regulatory reason to be legible.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/gs-oled-stale.png" class="img-fluid figure-img"></p>
<figcaption>Stale: silence during ascent is abnormal, so the state band says so and shows the age. Silence on the pad is normal and does not alarm.</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/gs-oled-summary.png" class="img-fluid figure-img"></p>
<figcaption>Summary: holds the peak until the next flight opens, because this is what I read walking downrange with the box in hand.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/gs-oled-overflow.png" class="img-fluid figure-img"></p>
<figcaption>Overflow policy: above 9,999 ft the hero switches units rather than shrinking or clipping, and truncates rather than rounds so it can never overstate altitude.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><em>Screens above are rendered by the ground station’s own drawing code, not mocked up.</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/v2-gs-oled-bench.jpg" class="img-fluid figure-img"></p>
<figcaption>The OLED on the bench during the redesign, showing an earlier layout with the 1834 ft test value.</figcaption>
</figure>
</div>
</section>
<section id="dashboard-and-power" class="level3">
<h3 class="anchored" data-anchor-id="dashboard-and-power">Dashboard and power</h3>
<p>A small Flask app inside the ingest service serves a phone-sized dashboard over the Pi’s Wi-Fi, which joins my phone’s hotspot at the range: per-vehicle flight badge and packet age, T+ since launch, AGL altitude, an RSSI sparkline and an events feed. It is a convenience path, not a data path. If the hotspot fails at the pad, capture, the panel and the OLED are all unaffected, which is why I was willing to close that item without ever observing an unattended cold-boot rejoin.</p>
<p>The PiSugar governs power both ways. Auto-shutdown at 5 % after 30 s, and a double-tap on its button runs an orderly shutdown so the append-only session log closes with a clean final record; a raw power cut can truncate the last line. Wake-on-charge fires on the rising edge of external power being connected, not on power being present, so a box powered off with the charger plugged in stays off. That rising-edge semantic is the fact I most expect to have forgotten in six months, which is why it is written next to the config.</p>
</section>
</section>
<section id="from-session-log-to-web-page" class="level2">
<h2 class="anchored" data-anchor-id="from-session-log-to-web-page">From session log to web page</h2>
<p>The flight archive is derived, never hand-edited. The ingest service writes one JSONL record per packet plus advisory events (flight open, flight close, service start and stop). A flights CLI segments a session into flights, derives each one, and exports a <code>flights.json</code> summary plus a per-flight CSV of raw packets, which the Quarto archive page reads directly.</p>
<p>The derivation that matters most is the <strong>AGL baseline</strong>. Raw barometric altitude at my bench reads about −85 ft. The baseline is a stability-gated trailing window over pad packets that locks the instant launch is detected, and both the baseline and the number of samples it used are stored with every flight so any AGL figure on the archive can be re-derived. The same pure function runs live on the ground station, on the handheld, and offline in the derivation, so the three never disagree about zero.</p>
<p>The first record in the archive, 2026-07-08-F1, is a bench shake test: a hand-swung sled tripped launch detection and ran the whole pipeline end to end, with a 10 ft “peak” that is barometric noise. Its real over-the-air bytes are now a version-controlled golden fixture that every contract change has to reproduce exactly.</p>
</section>
<section id="flight-day-2026-08-25" class="level2">
<h2 class="anchored" data-anchor-id="flight-day-2026-08-25">Flight day 2026-08-25</h2>
<p>Two Katana Jr flights on F15-6 motors at Izaak Walton Field, the first real 10 Hz flight records this system has produced. Both were on the archive page that evening.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Flight</th>
<th>Peak AGL</th>
<th>Packets</th>
<th>Loss</th>
<th>RSSI range</th>
<th>Max velocity</th>
<th>Max spin</th>
<th>Boost peak</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2026-08-25-F1</td>
<td>859 ft</td>
<td>3,222</td>
<td>0.31 %</td>
<td>−100 to −57 dBm</td>
<td>201 ft/s</td>
<td>1,177 dps</td>
<td>10.4 g</td>
</tr>
<tr class="even">
<td>2026-08-25-F2</td>
<td>749 ft</td>
<td>366</td>
<td>0.54 %</td>
<td>−97 to −69 dBm</td>
<td>—</td>
<td>2,299 dps</td>
<td>—</td>
</tr>
</tbody>
</table>
<p>F1’s record is long because the sled beaconed from the recovery grass for nine minutes before I reached it. F2 landed in an RF shadow at grass level and went quiet for 2.4 minutes after touchdown, which is the predicted recovery-beacon physics rather than flight loss. F2’s spin peak sits at the gyro’s full-scale limit, so the true rate is at least that.</p>
<p>The flights found three bugs, all fixed the same evening. Wall-clock timestamps on the Pi invert by about 33 ms on a 20-second cadence, and the derivation was manufacturing packet loss from the reordering; it now honours arrival order. Publishing overwrote the archive instead of merging into it, which would have erased July’s genesis record. And the publisher emitted a different schema than the page expected, so the new entries rendered as NaN until the page’s schema was pinned as the contract.</p>
<p>Three post-mortem items are still open with their evidence recorded and causes not chased: the box hard power-cut during pack-up at 95 % battery with no shutdown record, wake-on-charge did not fire on shore power at home, and the timestamp inversion itself is a Pi clock-discipline question whose durable fix is to record a monotonic time per packet.</p>
</section>
<section id="what-i-learned" class="level2">
<h2 class="anchored" data-anchor-id="what-i-learned">What I learned</h2>
<p><strong>Write the contract first.</strong> Everything downstream of ADR 0001 was cheap because both ends of the wire had a golden vector to fail against. When a newlib-nano printf quirk made every float tag encode empty on the real board, the end-to-end check caught it even though every host test passed.</p>
<p><strong>Test logic on the host, glue on the hardware.</strong> The firmware’s detectors, encoder, conversions and schedule are pure C++ with no Arduino includes and run natively on the Mac. The ground driver, decoder, derivation, OLED spec and LED policy are pure Python with time and transport injected. The Pi and the Feather only ever run thin shells. This is what made the sample-rate and apogee-latency numbers measurable before anything flew.</p>
<p><strong>State a fact once and cite it.</strong> On one day I found the clock escape-hatch procedure in four places, the LED order contradicting itself within a single document, and a state-file path wrong in two places while the constant was right. The convention now is that literal values live at one authority and everything else links to it.</p>
<p><strong>Ask whether a check could have failed.</strong> A test pipeline whose exit status was <code>tail</code>’s, a process check that matched its own command line, and a kill command that terminated the SSH session holding the pattern all happened in one day. Each reported success without verifying anything. The question to ask of any guard is not “did it pass” but “could this have failed”.</p>
<p><strong>A designed-but-inert signal is worse than an absent one.</strong> The RF LED cannot fire today because nothing publishes the counters it reads. That is recorded in one canonical table in the repo, and nothing may be described as panel-covered until it comes off that list.</p>
<p><strong>Don’t stack two revolutions without a flight between them.</strong> The Teensy 4.1 sled respin was decided in August, but sequenced firmly after the 10 Hz build flew on the Feather. A failure on an unflown RF rewrite and an unflown MCU port at the same time could not be attributed to either.</p>
</section>
<section id="whats-next" class="level2">
<h2 class="anchored" data-anchor-id="whats-next">What’s next</h2>
<ul>
<li><strong>Epic 5, Teensy 4.1 sled respin.</strong> Onboard Mahony fusion streaming a 10 Hz attitude, and the microSD flight recorder for spin spectra as a post-recovery product. The reasoning is in the link-budget section; the plan, port-cost audit and SD record design are written and waiting on hardware.</li>
<li><strong>Epic 7, the lander.</strong> A KB2040 with a BME680 and APDS9960 as <code>SRC:2</code>, separating at main and radioing its own atmosphere and light data home on the same grammar. The tag names are already reserved.</li>
<li><strong>Open hardening.</strong> Wire the RF LED and the write-failure leg of the red LED; record monotonic time per packet; chase the hard power-cut.</li>
<li><strong>The <a href="../projects/apogee-handheld.html">handheld</a> at a real launch.</strong> Family-tested on the bench, not yet flown.</li>
</ul>
</section>
<section id="links" class="level2">
<h2 class="anchored" data-anchor-id="links">Links</h2>
<ul>
<li><a href="https://github.com/velezf/lora-rocket-telemetry">GitHub repository</a></li>
<li><a href="../projects/lora-flights.html">Flight archive</a> and <a href="../projects/lora-radiorocket.html">V1 write-up</a></li>
<li><a href="../projects/apogee-handheld.html">Kids’ handheld</a></li>
<li>Decision records: <a href="https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/adr/0001-packet-format-v1.md">0001 packet format</a> · <a href="https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/adr/0002-ground-rx-driver-spidev.md">0002 native RX driver</a> · <a href="https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/adr/0003-rtc-boot-restore-clock-gate.md">0003 clock integrity</a> · <a href="https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/adr/0005-telemetry-rate-and-rf-configuration.md">0005 rate and RF</a></li>
<li><a href="https://github.com/velezf/lora-rocket-telemetry/tree/main/firmware">Sled firmware</a> · <a href="https://github.com/velezf/lora-rocket-telemetry/tree/main/ground">Ground service</a> · <a href="https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/field-checklist.md">Field checklist</a></li>
<li>Original concept: <a href="https://github.com/N3VEM/RadioRocketV2">N3VEM’s RadioRocketV2</a></li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "LoRa RadioRocket V2"</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Second-generation rocket telemetry: a Raspberry Pi 5 ground station that receives LoRa natively in Python, a versioned packet contract shared by every node, 10 Hz flight-rate telemetry with onboard velocity and G envelopes, a fail-closed LED panel beside a status OLED, and a flight archive that publishes itself. Two Katana Jr flights recorded at under 1 % packet loss."</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-09-05"</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [IoT, telemetry, LoRa, hardware, amateur radio, Raspberry Pi, Python, embedded]</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="an">image:</span><span class="co"> ../images/lora-radiorocket-v2.jpg</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">## Overview</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Version 1</span><span class="co">](lora-radiorocket.qmd)</span> proved that a Feather M0 in a rocket could stream altitude and G-force to a LePotato on the ground at 1 Hz. It worked on its first flight, and it also taught me what a link is not: it is not a record. The V1 string was unversioned, a second receiver could not be added without copying code, the ground side depended on Node-RED flows I could not test, and a whole flight was about twenty data points.</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>V2 kept the sled and rebuilt everything around it. The ground station is now a Raspberry Pi 5 that receives LoRa **natively** through a driver I wrote in Python, so there is no RX firmware at all. The packet format is a written, versioned contract that a C encoder on the sled and a Python decoder on the ground both test against. The sled samples at 20 Hz and transmits at 10 Hz in flight. Every flight lands in an append-only session log, is derived into a permalinked record, and appears on the <span class="co">[</span><span class="ot">flight archive</span><span class="co">](lora-flights.qmd)</span> the same evening. A separate <span class="co">[</span><span class="ot">kids' handheld</span><span class="co">](apogee-handheld.qmd)</span> listens to the same broadcast.</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>This page is the V2 write-up. The V1 page and the flight archive stay as they are.</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="fu">## Status, 2026-09-05</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>Flown and recording. Two Katana Jr flights on 2026-08-25 produced the first real 10 Hz flight records (859 ft and 749 ft AGL, 0.31 % and 0.54 % packet loss). The handheld is built and family-tested. Still ahead: a Teensy 4.1 sled respin with onboard attitude fusion and an SD flight recorder, the deployable lander payload, and a launch-day trial of the handheld game.</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>📡 **[Flight archive →](lora-flights.qmd)** — every record, with AGL altitude, link quality, and full 10 Hz traces.</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="fu">## What changed from V1</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="pp">|</span> V1 (2025) <span class="pp">|</span> V2 (2026) <span class="pp">|</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Ground computer <span class="pp">|</span> Libre LePotato + a second Feather M0 as RX <span class="pp">|</span> Raspberry Pi 5 (8 GB), radio on the Pi's own SPI bus <span class="pp">|</span></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Receiver code <span class="pp">|</span> Arduino RX firmware, serial to Node-RED <span class="pp">|</span> Python SX127x driver over <span class="in">`spidev`</span> + <span class="in">`lgpio`</span>, host-tested against a fake SPI <span class="pp">|</span></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Packet format <span class="pp">|</span> Ad hoc string with emoji and a space-bearing battery status <span class="pp">|</span> Versioned <span class="in">`KEY:VALUE`</span> ASCII contract (ADR 0001), additive tags, tolerant decoders <span class="pp">|</span></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Telemetry rate <span class="pp">|</span> 1 Hz, sampled and transmitted in the same loop <span class="pp">|</span> 20 Hz sampling; 1 Hz on the pad, 10 Hz in flight (ADR 0005) <span class="pp">|</span></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Radio <span class="pp">|</span> 434 MHz, BW 125 kHz, 23 dBm <span class="pp">|</span> 434 MHz, SF7 / BW 500 kHz / CR 4:5, 17 dBm <span class="pp">|</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Fields <span class="pp">|</span> ALT, Max, G, Pg, T, Batt, state <span class="pp">|</span> Same, plus SEQ, MET, onboard <span class="in">`Vel`</span>, G envelope <span class="in">`Gmx`</span>/<span class="in">`Gmn`</span>, spin envelope <span class="in">`Wmx`</span>, 9-DoF pad frames, <span class="in">`CALL`</span> beacons <span class="pp">|</span></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Flight record <span class="pp">|</span> Whatever the dashboard showed <span class="pp">|</span> Append-only JSONL session log, derived flights index, published CSV per flight <span class="pp">|</span></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Status at the pad <span class="pp">|</span> Laptop dashboard <span class="pp">|</span> Six-LED panel (own process, fail-closed), 128×64 OLED, phone dashboard over hotspot <span class="pp">|</span></span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Clock <span class="pp">|</span> Whatever the SBC booted with <span class="pp">|</span> PiSugar RTC restore at boot and a fail-closed clock gate before any session opens <span class="pp">|</span></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Testing <span class="pp">|</span> Flash and see <span class="pp">|</span> Host-side TDD for every piece of logic: 88 native firmware tests, 400 ground tests, 83 handheld tests <span class="pp">|</span></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Other receivers <span class="pp">|</span> None <span class="pp">|</span> Kids' handheld on a Pi Zero 2 W, importing the ground decoder unchanged <span class="pp">|</span></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>The APRS digipeater side of the V1 box (RTL-SDR + Direwolf) carried over into the V2 enclosure, but it is not part of this telemetry system and I have left it out of this write-up.</span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a><span class="fu">## System architecture</span></span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a><span class="in">```{mermaid}</span></span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>%%| fig-cap: <span class="ot">"</span><span class="st">One transmitter, many listeners. The sled is the only C++ in the project; everything on the ground is Python.</span><span class="ot">"</span></span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>flowchart LR</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>  subgraph rocket[<span class="ot">"</span><span class="st">Rocket sled — SRC:1</span><span class="ot">"</span>]</span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a>    FW[<span class="ot">"</span><span class="st">Feather M0 + RFM96&lt;br/&gt;BMP390 · ADXL375 · 9-DoF&lt;br/&gt;20 Hz sample · 1/10 Hz TX</span><span class="ot">"</span>]</span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>  end</span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a>  FW -- <span class="ot">"</span><span class="st">434 MHz LoRa&lt;br/&gt;V:1 KEY:VALUE frames</span><span class="ot">"</span> --&gt; RX</span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a>  FW -. broadcast .-&gt; HH[<span class="ot">"</span><span class="st">Kids' handheld&lt;br/&gt;Pi Zero 2 W + bonnet</span><span class="ot">"</span>]</span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a>  subgraph gs[<span class="ot">"</span><span class="st">Ground station — apogee-gs (Pi 5)</span><span class="ot">"</span>]</span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a>    RX[<span class="ot">"</span><span class="st">sx127x driver&lt;br/&gt;spidev + lgpio</span><span class="ot">"</span>] --&gt; ING[<span class="ot">"</span><span class="st">apogee-ingest&lt;br/&gt;decode · link stats · flight detect</span><span class="ot">"</span>]</span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a>    ING --&gt; LOG[<span class="ot">"</span><span class="st">session JSONL&lt;br/&gt;append-only</span><span class="ot">"</span>]</span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a>    ING --&gt; DASH[<span class="ot">"</span><span class="st">Flask dashboard&lt;br/&gt;phone hotspot</span><span class="ot">"</span>]</span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a>    ING --&gt; OLED[<span class="ot">"</span><span class="st">128×64 OLED&lt;br/&gt;what the flight is doing</span><span class="ot">"</span>]</span>
<span id="cb3-59"><a href="#cb3-59" aria-hidden="true" tabindex="-1"></a>    ING -- heartbeat --&gt; PANEL[<span class="ot">"</span><span class="st">apogee-panel&lt;br/&gt;6 LEDs · is the system working</span><span class="ot">"</span>]</span>
<span id="cb3-60"><a href="#cb3-60" aria-hidden="true" tabindex="-1"></a>  end</span>
<span id="cb3-61"><a href="#cb3-61" aria-hidden="true" tabindex="-1"></a>  LOG --&gt; FLT[<span class="ot">"</span><span class="st">flights CLI&lt;br/&gt;segment · derive AGL · export</span><span class="ot">"</span>]</span>
<span id="cb3-62"><a href="#cb3-62" aria-hidden="true" tabindex="-1"></a>  FLT --&gt; WEB[<span class="ot">"</span><span class="st">flights.json + CSV&lt;br/&gt;velezf.github.io</span><span class="ot">"</span>]</span>
<span id="cb3-63"><a href="#cb3-63" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-64"><a href="#cb3-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-65"><a href="#cb3-65" aria-hidden="true" tabindex="-1"></a>The shape that matters is on the right: one process owns the radio and fans decoded observations out to consumers, and time is injected into that observation once. No consumer reads a clock. Three files are written by three different writers, never shared: the session log by the service, an ops journal by the CLI, and the flights index by pure derivation from the other two. Rebuilding the index from the same inputs produces byte-identical output, which is what lets me trust a number on the archive page months later.</span>
<span id="cb3-66"><a href="#cb3-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-67"><a href="#cb3-67" aria-hidden="true" tabindex="-1"></a><span class="fu">## The packet contract</span></span>
<span id="cb3-68"><a href="#cb3-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-69"><a href="#cb3-69" aria-hidden="true" tabindex="-1"></a>The single most useful decision in V2 was writing the wire format down before touching either end. <span class="co">[</span><span class="ot">ADR 0001</span><span class="co">](https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/adr/0001-packet-format-v1.md)</span> defines a v1 packet as space-delimited ASCII tokens, each a <span class="in">`KEY:VALUE`</span> pair, the first always <span class="in">`V:1`</span>:</span>
<span id="cb3-70"><a href="#cb3-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-71"><a href="#cb3-71" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-72"><a href="#cb3-72" aria-hidden="true" tabindex="-1"></a><span class="in">V:1 SYS:7 SRC:1 SEQ:42 St:1 ALT:1234ft Max:5678ft G:2.3 Pg:9.1 T:21.5C Batt:3.92V MET:12</span></span>
<span id="cb3-73"><a href="#cb3-73" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-74"><a href="#cb3-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-75"><a href="#cb3-75" aria-hidden="true" tabindex="-1"></a>That exact string is a golden vector. The C encoder on the sled and the Python decoder on the ground each carry a unit test that asserts against it, so the two implementations can only drift by failing a test. The rules that make it evolvable:</span>
<span id="cb3-76"><a href="#cb3-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-77"><a href="#cb3-77" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Keyed, not positional.** A decoder keys on tag names, ignores tags it does not know, and tolerates absent ones. A missing tag is valid, not an error.</span>
<span id="cb3-78"><a href="#cb3-78" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Additive changes do not bump the version.** <span class="in">`Vel`</span>, <span class="in">`Gmx`</span>, <span class="in">`Gmn`</span>, <span class="in">`Wmx`</span> and the 9-DoF pad-frame channels were all added within v1 without touching any deployed receiver.</span>
<span id="cb3-79"><a href="#cb3-79" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Only breaking changes bump `V`.** Renaming a tag, changing its units, or changing the grammar. A decoder that sees an unknown version must reject the packet and count it, never best-effort parse.</span>
<span id="cb3-80"><a href="#cb3-80" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Addressing rides in the payload.** <span class="in">`SYS`</span> is the network, <span class="in">`SRC`</span> the vehicle (1 sled, 2 lander). Because they are in the string and not in a radio header, the contract is transport-agnostic.</span>
<span id="cb3-81"><a href="#cb3-81" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Integrity is the LoRa PHY CRC.** No application checksum in v1; the driver drops and counts CRC failures before the decoder ever sees them.</span>
<span id="cb3-82"><a href="#cb3-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-83"><a href="#cb3-83" aria-hidden="true" tabindex="-1"></a>ASCII costs airtime. A 139-byte frame carries about fifteen numbers that would pack into thirty bytes, a tax of roughly four times. I kept it deliberately: every defect I have found in this project so far was found by reading a session log or a serial console with my eyes, and a binary format would take that away. It is recorded as the next lever if I ever need more than about 17 packets per second, since bandwidth is exhausted at BW 500.</span>
<span id="cb3-84"><a href="#cb3-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-85"><a href="#cb3-85" aria-hidden="true" tabindex="-1"></a><span class="fu">## The sled: sample fast, transmit slow</span></span>
<span id="cb3-86"><a href="#cb3-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-87"><a href="#cb3-87" aria-hidden="true" tabindex="-1"></a><span class="al">![The V2 sled board set before assembly: Feather M0 RFM96 with the quarter-wave wire antenna, BMP390 barometer, ADXL375 high-G accelerometer (±200 g), LSM6DSOX + LIS3MDL 9-DoF, and a 350 mAh LiPo.](https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/v2-sled-boards.jpg)</span></span>
<span id="cb3-88"><a href="#cb3-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-89"><a href="#cb3-89" aria-hidden="true" tabindex="-1"></a>The V1 firmware sampled and transmitted in the same loop, gated by a one-second delay. The consequence showed up on the first V2 bench test: a hand-swung sled produced a 2.2 g jerk that fell between samples and never tripped launch detection. The detectors were only as fast as the radio.</span>
<span id="cb3-90"><a href="#cb3-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-91"><a href="#cb3-91" aria-hidden="true" tabindex="-1"></a>V2 splits them. The loop samples the barometer and accelerometers on a 50 ms tick and transmits on a separate schedule. A failed barometer read now skips that one sample instead of returning from the whole loop and costing a packet. The firmware measures and prints its own achieved sample rate every five seconds, because the BMP390's throughput at a given oversampling is a property to measure, not to assume. It first came in at 17 Hz; the missing time turned out to be the radio library busy-waiting on the previous transmission, not the barometer, and making the transmit non-blocking brought it to 20 Hz.</span>
<span id="cb3-92"><a href="#cb3-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-93"><a href="#cb3-93" aria-hidden="true" tabindex="-1"></a><span class="fu">### Confirmed apogee, and the harness that measured it</span></span>
<span id="cb3-94"><a href="#cb3-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-95"><a href="#cb3-95" aria-hidden="true" tabindex="-1"></a>The V1 apogee detector declared apogee on the first sample that was not higher than the running max, and latched. One noisy sample during boost could set the descent state for the rest of the flight, and every subsequent packet would carry a wrong flight state that no ground-side processing could recover, because the truth was never transmitted.</span>
<span id="cb3-96"><a href="#cb3-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-97"><a href="#cb3-97" aria-hidden="true" tabindex="-1"></a>V2's detector requires 20 ft of hysteresis below the running max **and** 300 ms of continuous dwell, with both constants in time rather than sample counts so a slower achieved rate degrades precision instead of silently redefining the criterion. To size it I built a synthetic flight profile with an analytic ground truth and a harness that runs any detector at any sample rate. It immediately corrected a threefold arithmetic error in my own plan: confirmed-apogee latency costs 77.9 ft of altitude at 1 Hz and 33.8 ft at 20 Hz, not the 257 and 27 I had estimated, and most of the benefit is already won by 5 Hz.</span>
<span id="cb3-98"><a href="#cb3-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-99"><a href="#cb3-99" aria-hidden="true" tabindex="-1"></a><span class="fu">### Why 10 Hz needed a bandwidth change</span></span>
<span id="cb3-100"><a href="#cb3-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-101"><a href="#cb3-101" aria-hidden="true" tabindex="-1"></a>A whole flight of this class is about twenty seconds. At 1 Hz that is twenty points, enough to say a flight happened, not enough to plot it. The target that drove <span class="co">[</span><span class="ot">ADR 0005</span><span class="co">](https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/adr/0005-telemetry-rate-and-rf-configuration.md)</span> was an OpenRocket-style plot: altitude, vertical velocity and acceleration against time, with event markers.</span>
<span id="cb3-102"><a href="#cb3-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-103"><a href="#cb3-103" aria-hidden="true" tabindex="-1"></a>Three LoRa parameters set throughput. The coding rate was already minimal. SF6 would have required implicit-header fixed-length packets, which fights the variable-length tolerant format at the mechanism level. That left bandwidth:</span>
<span id="cb3-104"><a href="#cb3-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-105"><a href="#cb3-105" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Bandwidth <span class="pp">|</span> Time on air, 139 B <span class="pp">|</span> Duty at 10 Hz <span class="pp">|</span> Sensitivity <span class="pp">|</span></span>
<span id="cb3-106"><a href="#cb3-106" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb3-107"><a href="#cb3-107" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 125 kHz (V1) <span class="pp">|</span> 235.8 ms <span class="pp">|</span> 236 %, impossible <span class="pp">|</span> −123 dBm <span class="pp">|</span></span>
<span id="cb3-108"><a href="#cb3-108" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 250 kHz <span class="pp">|</span> 117.9 ms <span class="pp">|</span> 118 %, impossible <span class="pp">|</span> −120 dBm <span class="pp">|</span></span>
<span id="cb3-109"><a href="#cb3-109" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **500 kHz** | **58.9 ms** | **58.9 %** | **−117 dBm** <span class="pp">|</span></span>
<span id="cb3-110"><a href="#cb3-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-111"><a href="#cb3-111" aria-hidden="true" tabindex="-1"></a>At the V1 bandwidth 10 Hz was not expensive, it was unreachable. Going to 500 kHz costs 6 dB of sensitivity, and whether the link could afford that is the question the next section is about. TX power dropped from 23 to 17 dBm as part of the same decision, because at 59 % duty the transmitter is keyed more than half the time and heat becomes the binding constraint.</span>
<span id="cb3-112"><a href="#cb3-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-113"><a href="#cb3-113" aria-hidden="true" tabindex="-1"></a>Transmit rate is state-dependent: 1 Hz on the pad, 10 Hz from confirmed launch for a 300 s window bounded by mission elapsed time, then back to a 1 Hz recovery beacon. The window is bounded by MET because nothing else bounds it; without a landed state code, "fast while airborne" would key the transmitter until the battery died in the grass.</span>
<span id="cb3-114"><a href="#cb3-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-115"><a href="#cb3-115" aria-hidden="true" tabindex="-1"></a><span class="fu">### What rides on the wire now</span></span>
<span id="cb3-116"><a href="#cb3-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-117"><a href="#cb3-117" aria-hidden="true" tabindex="-1"></a>Three fields were added within v1 for the plot, and the reasoning behind each is in the link-budget section below: <span class="in">`Vel`</span>, vertical velocity computed on board at the sample rate; <span class="in">`Gmx`</span> and <span class="in">`Gmn`</span>, the acceleration envelope across each transmit window; and <span class="in">`Wmx`</span>, the same window mechanism over gyro magnitude so spin cannot alias however fast the airframe rolls.</span>
<span id="cb3-118"><a href="#cb3-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-119"><a href="#cb3-119" aria-hidden="true" tabindex="-1"></a>Frame shape follows flight state: pad frames carry the raw 9-DoF channels at 1 Hz as a calibration dataset, flight frames carry the envelopes. Every transmitter also beacons its callsign (KC3ZTQ) at start, at least every 9.5 minutes, and at shutdown, per Part 97. Beacons are counted separately and never participate in flight accounting: a landed rocket beaconing every minute must not hold a flight open.</span>
<span id="cb3-120"><a href="#cb3-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-121"><a href="#cb3-121" aria-hidden="true" tabindex="-1"></a><span class="fu">## Learning link budgets, and what they decided</span></span>
<span id="cb3-122"><a href="#cb3-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-123"><a href="#cb3-123" aria-hidden="true" tabindex="-1"></a>I came into V2 without ever having done a link budget. V1 worked, so I had never needed one. V2 forced the question three separate times, and each time the arithmetic ended up choosing a design I would not have picked by intuition. This section is the elementary version, written the way I worked it out.</span>
<span id="cb3-124"><a href="#cb3-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-125"><a href="#cb3-125" aria-hidden="true" tabindex="-1"></a><span class="fu">### The arithmetic</span></span>
<span id="cb3-126"><a href="#cb3-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-127"><a href="#cb3-127" aria-hidden="true" tabindex="-1"></a>A link budget is bookkeeping in decibels. Start with what the transmitter puts out, subtract what the path takes away, and compare what is left against the weakest signal the receiver can still decode. Free-space path loss for a distance *d* in kilometres at frequency *f* in megahertz is</span>
<span id="cb3-128"><a href="#cb3-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-129"><a href="#cb3-129" aria-hidden="true" tabindex="-1"></a>$$\text{FSPL} = 32.44 + 20\log_{10}(f) + 20\log_{10}(d)$$</span>
<span id="cb3-130"><a href="#cb3-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-131"><a href="#cb3-131" aria-hidden="true" tabindex="-1"></a>For 434 MHz and a worst-case slant range of 1.5 km, which is generous for the flights this system flies:</span>
<span id="cb3-132"><a href="#cb3-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-133"><a href="#cb3-133" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-134"><a href="#cb3-134" aria-hidden="true" tabindex="-1"></a><span class="in">FSPL   = 32.44 + 20·log10(434) + 20·log10(1.5) = 88.7 dB</span></span>
<span id="cb3-135"><a href="#cb3-135" aria-hidden="true" tabindex="-1"></a><span class="in">RX     = 17 dBm − 88.7 dB                        = −71.7 dBm   (0 dBi antennas both ends)</span></span>
<span id="cb3-136"><a href="#cb3-136" aria-hidden="true" tabindex="-1"></a><span class="in">margin = −71.7 − (−117)                          = 45.3 dB</span></span>
<span id="cb3-137"><a href="#cb3-137" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-138"><a href="#cb3-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-139"><a href="#cb3-139" aria-hidden="true" tabindex="-1"></a>Subtract 2 to 3 dB for connectors and cable and call it 42 dB. The number that gave me confidence was not the clear-air figure but what it leaves for fading: a tumbling airframe sweeps its antenna pattern through deep nulls, and 20 to 30 dB fades are ordinary. A 42 dB margin absorbs a 30 dB fade with room left.</span>
<span id="cb3-140"><a href="#cb3-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-141"><a href="#cb3-141" aria-hidden="true" tabindex="-1"></a>The −117 dBm in that sum is the receiver's sensitivity, and this is where bandwidth entered. LoRa sensitivity gets 3 dB worse every time bandwidth doubles, because the receiver is integrating noise over twice the spectrum. 125 kHz gives −123 dBm, 500 kHz gives −117 dBm. So the 10 Hz decision was really the sentence "I am spending 6 dB of my 48 dB on time", and the budget said I could.</span>
<span id="cb3-142"><a href="#cb3-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-143"><a href="#cb3-143" aria-hidden="true" tabindex="-1"></a>Two other pieces of the picture were new to me. Duty cycle is not a regulatory limit under Part 97, so it shows up as a thermal constraint on the transmitter, which is why TX power dropped to 17 dBm as part of the same decision. And the 500 kHz channel centred on 434.0 MHz occupies 433.75 to 434.25 MHz, inside the 70 cm amateur allocation, where amateur is secondary and the band is shared with a great deal of 433 MHz ISM traffic. That is a noise-floor consideration, not a legality one, and it is the argument for keeping margin rather than spending all of it.</span>
<span id="cb3-144"><a href="#cb3-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-145"><a href="#cb3-145" aria-hidden="true" tabindex="-1"></a><span class="fu">### The antenna I did not know was missing</span></span>
<span id="cb3-146"><a href="#cb3-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-147"><a href="#cb3-147" aria-hidden="true" tabindex="-1"></a>The budget is a design assumption until something measures it, and the first measurement said the design was fiction. Bench RSSI at a few feet had been sitting around −80 dBm when the recorded bench band for that geometry was −38 to −14 dBm. Somewhere between 42 and 66 dB of the budget was simply not there. The receive chain had a re-soldered u.FL connector and a damaged bulkhead pigtail, and until they were fixed every weak-signal symptom was the connector until proven otherwise. After the repair, close-range RSSI came back to −40 ±1 dBm with zero loss and a standard deviation of 0.38 dB over 45 packets, 2 dB shy of the bench band and attributed to the insertion loss of the new connector chain.</span>
<span id="cb3-148"><a href="#cb3-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-149"><a href="#cb3-149" aria-hidden="true" tabindex="-1"></a>Only a flight could measure the rest. On 2026-08-25 the worst in-flight RSSI was −101 dBm at about 860 ft, against −117 dBm sensitivity: 16 dB of real margin at the worst moment of the flight, fades included, at less than a fifth of the range the budget was sized for. That number replaced the design assumption in the ADR, and the packet loss it came with was 0.31 %.</span>
<span id="cb3-150"><a href="#cb3-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-151"><a href="#cb3-151" aria-hidden="true" tabindex="-1"></a><span class="fu">### What good ADXL375 data needed</span></span>
<span id="cb3-152"><a href="#cb3-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-153"><a href="#cb3-153" aria-hidden="true" tabindex="-1"></a>The high-G accelerometer is the sled's launch detector and its only view of boost, and V1 was wasting it. The first V2 bench test made that concrete: a hand swing produced a 2.2 g jerk that fell between two 1 Hz samples and never tripped the 3 g launch threshold. The sensor saw it; the loop did not.</span>
<span id="cb3-154"><a href="#cb3-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-155"><a href="#cb3-155" aria-hidden="true" tabindex="-1"></a>The link budget decided how this got fixed, because every option cost bytes on the wire, and bytes are airtime, and airtime is the thing the budget had just priced.</span>
<span id="cb3-156"><a href="#cb3-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-157"><a href="#cb3-157" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Sample fast, transmit slow.** Decoupling the sample tick from the transmit tick cost nothing in airtime, so it came first. The ADXL375 is now read every 50 ms regardless of when the radio next keys up.</span>
<span id="cb3-158"><a href="#cb3-158" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Send the envelope, not the sample.** Even at 10 Hz, an instantaneous reading misses a spike that lasts 20 ms, and the plotted amplitude would depend on which phase of the boost the sample happened to land in. The fix is to compute the minimum and maximum acceleration magnitude across each transmit window on board and send both, reset only when a frame actually goes to air, so a skipped transmission widens the window rather than losing the spike. That makes spike amplitudes exact at any transmit rate, which decouples the accelerometer's correctness from the rate decision entirely.</span>
<span id="cb3-159"><a href="#cb3-159" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Budget the bytes.** Those two tags plus onboard velocity took the worst-case frame from 109 to 141 bytes, which is why the airtime table above is computed at 139 and why the decision is 58.9 % duty rather than 45 %. An earlier increment that tried to send the three raw axes found the firmware's message buffer was 128 bytes against a 143-byte worst case, and that truncation was silent: a frame cut short decoded as a valid packet with a plausible wrong value. Both the buffer and the encoder were fixed so overflow is loud, and the per-axis tags were parked because the envelope answers the question they were asked for.</span>
<span id="cb3-160"><a href="#cb3-160" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**What not to send.** Splitting slow-changing tags across alternate packets would have saved about 13 % of airtime and made "absent" indistinguishable from "unchanged" for every consumer. The budget had already bought enough headroom that the complexity had nothing to purchase.</span>
<span id="cb3-161"><a href="#cb3-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-162"><a href="#cb3-162" aria-hidden="true" tabindex="-1"></a>The principle that fell out, and that the next subsection extends, is to derive where the data is dense and transmit the derivative. Velocity is computed on board at 20 Hz because differentiating 10 Hz altitude on the ground amplifies the barometer's quantisation into noise. The G envelope is computed on board for the same reason.</span>
<span id="cb3-163"><a href="#cb3-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-164"><a href="#cb3-164" aria-hidden="true" tabindex="-1"></a><span class="fu">### Why attitude pushed me to a Teensy</span></span>
<span id="cb3-165"><a href="#cb3-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-166"><a href="#cb3-166" aria-hidden="true" tabindex="-1"></a>The 9-DoF sensors are on the sled, and the obvious plan was to stream their raw gyro and accelerometer values and fuse them into an attitude on the Pi. The link budget closed that door in one afternoon of arithmetic.</span>
<span id="cb3-167"><a href="#cb3-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-168"><a href="#cb3-168" aria-hidden="true" tabindex="-1"></a>Fusion needs raw samples at 50 Hz or more. At SF7 and 500 kHz, ASCII raw frames at 50 Hz come to 352 % duty. A minimal 20-byte binary frame per sample is 77 %, over the 65 % line I had set for thermal reasons. A realistic 34-byte binary frame is 103 %, over the radio's ceiling itself. Batching five samples into a 10 Hz binary packet does fit, at about 32 % duty, so duty alone does not close the question. Two other legs do. Batching requires a binary v2 format, the largest contract change the system could make. And the load-bearing one: attitude is an integration, and integrating over a lossy radio link means every tumble fade punches a hole in the input and the solution diverges during exactly the dynamics it exists to capture. Onboard integration has a loss-free input by construction. No transport fixes that.</span>
<span id="cb3-169"><a href="#cb3-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-170"><a href="#cb3-170" aria-hidden="true" tabindex="-1"></a>So attitude is computed on board or it does not exist live. That put the question to the Feather M0, a 48 MHz Cortex-M0+ with no floating-point unit: could it run a Mahony filter at 100 Hz in software floats alongside everything it already does? I never had to measure it. The Teensy 4.1 was already on hand, and its 600 MHz Cortex-M7 with an FPU makes the question moot, while its built-in microSD slot becomes the full-rate flight recorder for the one product the radio can never carry, spin spectra from the IMU FIFO at 833 Hz. The plan runs the core down to 150 MHz, which roughly quarters the MCU's draw; in flight the radio at 17 dBm and 59 % duty dominates the power budget anyway, so the clock is a pad-endurance knob rather than a flight one.</span>
<span id="cb3-171"><a href="#cb3-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-172"><a href="#cb3-172" aria-hidden="true" tabindex="-1"></a>The port cost was measured before deciding. Every firmware unit in <span class="in">`lib/`</span> has zero board includes, so the detectors, encoder, conversions and the profile harness move without edits along with their native tests. The entire port surface is the one hardware glue file, and the two things that do not carry over are the Feather's hardwired radio pins and its battery-sense divider, which is board wiring and would silently produce plausible wrong volts if forgotten.</span>
<span id="cb3-173"><a href="#cb3-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-174"><a href="#cb3-174" aria-hidden="true" tabindex="-1"></a>Sequencing was firm: the 10 Hz build flew on the Feather first. Stacking an unflown MCU port on an unflown RF rewrite would have meant failures that could not be attributed to either.</span>
<span id="cb3-175"><a href="#cb3-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-176"><a href="#cb3-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-177"><a href="#cb3-177" aria-hidden="true" tabindex="-1"></a><span class="fu">## The ground station</span></span>
<span id="cb3-178"><a href="#cb3-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-179"><a href="#cb3-179" aria-hidden="true" tabindex="-1"></a><span class="al">![Inside the V2 box, lid off. The Pi 5 sits under a proto-board carrier; the RFM96W breakout on its SPI bus feeds the left bulkhead SMA through a u.FL pigtail. The RTL-SDR on the right serves the APRS digipeater. The 1.3" OLED is taped in for the bench.](https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/v2-gs-interior.jpg)</span></span>
<span id="cb3-180"><a href="#cb3-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-181"><a href="#cb3-181" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Component <span class="pp">|</span> Role <span class="pp">|</span></span>
<span id="cb3-182"><a href="#cb3-182" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb3-183"><a href="#cb3-183" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Raspberry Pi 5 (8 GB), Pi OS 64-bit Trixie <span class="pp">|</span> Runs the ingest service, dashboard, OLED and panel supervisor <span class="pp">|</span></span>
<span id="cb3-184"><a href="#cb3-184" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> RFM96W breakout on SPI0, CE1 <span class="pp">|</span> Native LoRa receive; DIO0 deliberately unwired, the driver polls <span class="pp">|</span></span>
<span id="cb3-185"><a href="#cb3-185" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Adafruit 1.3" SSD1306 128×64 OLED on I²C <span class="pp">|</span> Flight display <span class="pp">|</span></span>
<span id="cb3-186"><a href="#cb3-186" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Six front-panel LEDs on GPIO <span class="pp">|</span> System-health panel, driven by its own process <span class="pp">|</span></span>
<span id="cb3-187"><a href="#cb3-187" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> PiSugar 3 Plus UPS, 5000 mAh <span class="pp">|</span> Battery, real-time clock, graceful shutdown, wake-on-charge <span class="pp">|</span></span>
<span id="cb3-188"><a href="#cb3-188" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 12 V → 5 V buck into the PiSugar charge port <span class="pp">|</span> Field power from a vehicle or pack <span class="pp">|</span></span>
<span id="cb3-189"><a href="#cb3-189" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Blue metal project box, run lid-off <span class="pp">|</span> Airflow over passive heatsinks and no shielding of the Pi's Wi-Fi <span class="pp">|</span></span>
<span id="cb3-190"><a href="#cb3-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-191"><a href="#cb3-191" aria-hidden="true" tabindex="-1"></a>::: {layout-ncol=2}</span>
<span id="cb3-192"><a href="#cb3-192" aria-hidden="true" tabindex="-1"></a><span class="al">![The PiSugar 3 Plus mounts under the Pi on pogo pins. Both the Pi 5 and the Zero needed a bit of solder on the pogo pads before the I²C interface showed up.](https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/v2-gs-pisugar.jpg)</span></span>
<span id="cb3-193"><a href="#cb3-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-194"><a href="#cb3-194" aria-hidden="true" tabindex="-1"></a><span class="al">![Front panel: the SCE-to-AUX switch carried over from V1, and the six-LED row. Blue, blue, red, green, green, green, left to right.](https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/v2-gs-front-panel.jpg)</span></span>
<span id="cb3-195"><a href="#cb3-195" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-196"><a href="#cb3-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-197"><a href="#cb3-197" aria-hidden="true" tabindex="-1"></a><span class="fu">### Native receive, no RX firmware</span></span>
<span id="cb3-198"><a href="#cb3-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-199"><a href="#cb3-199" aria-hidden="true" tabindex="-1"></a>The plan called for Adafruit's <span class="in">`rfm9x`</span> library on Blinka. On the Pi 5 that fell apart: <span class="in">`RPi.GPIO`</span> maps BCM283x registers directly and does not run on the Pi 5's RP1, and Blinka's build pulled in dependencies that would not compile in an isolated venv. Rather than shim it, I wrote a small SX127x driver over raw <span class="in">`spidev`</span> and <span class="in">`lgpio`</span> (<span class="co">[</span><span class="ot">ADR 0002</span><span class="co">](https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/adr/0002-ground-rx-driver-spidev.md)</span>). It mirrors the sled's RadioHead modem configuration, enforces the CRC, strips the four-byte RadioHead header, and hands validated payload bytes to the decoder. The SPI transport is injected, so register and frame logic run on my Mac against a fake SPI with no hardware.</span>
<span id="cb3-200"><a href="#cb3-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-201"><a href="#cb3-201" aria-hidden="true" tabindex="-1"></a>The whole ground stack ended up Blinka-free: OLED via <span class="in">`luma.oled`</span>, LEDs via <span class="in">`lgpio`</span>, radio via <span class="in">`spidev`</span>. The radio is receive-only by construction, not by convention: the driver defines only sleep, standby and continuous-receive modes, and no transmit or power-amplifier register is ever written. That is what makes it safe to power the box without an antenna while a pigtail is on order. The sled has the opposite rule and never runs without one.</span>
<span id="cb3-202"><a href="#cb3-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-203"><a href="#cb3-203" aria-hidden="true" tabindex="-1"></a><span class="fu">### The clock problem</span></span>
<span id="cb3-204"><a href="#cb3-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-205"><a href="#cb3-205" aria-hidden="true" tabindex="-1"></a>Every session and record is timestamped from the system clock at the moment the radio owner sees the frame. On 2026-07-13 the box booted with a mis-dated session, and the chain was instructive. The Pi 5's onboard RTC has no coin cell, so the kernel came up in 1970. The time-sync daemon then advanced the clock to its saved floor, the last shutdown time. Nothing had read the PiSugar's battery-backed RTC, which was correct. My old gate checked that the year was at least 2024, the stale floor passed it, and a session opened four days in the past. Wi-Fi fixed it that time; offline at a launch site it would have been a silently corrupt record.</span>
<span id="cb3-206"><a href="#cb3-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-207"><a href="#cb3-207" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">ADR 0003</span><span class="co">](https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/adr/0003-rtc-boot-restore-clock-gate.md)</span> fixed it in two coupled parts. A oneshot unit reads the PiSugar RTC before ingest starts and sets the system clock only when it is bogus or grossly behind, never stepping backward, and drops a trust marker. The ingest service then refuses to start unless the clock is NTP-synced or that marker exists. A plausible year alone no longer passes. For the case of a dead RTC and no network there is an operator escape hatch: set the clock from a phone and attest it. Silence and duration inside the service use monotonic deltas, so a later clock step cannot distort a flight's length. The whole thing was verified on a cold boot with Wi-Fi off.</span>
<span id="cb3-208"><a href="#cb3-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-209"><a href="#cb3-209" aria-hidden="true" tabindex="-1"></a><span class="fu">### Two surfaces, not peers</span></span>
<span id="cb3-210"><a href="#cb3-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-211"><a href="#cb3-211" aria-hidden="true" tabindex="-1"></a>The box has two displays and they answer different questions. The LED panel answers "is the system working". The OLED answers "what is the flight doing". The distinction is structural. The panel supervisor is its own process that reads a heartbeat file the ingest service publishes; when ingest dies the heartbeat goes stale and the supervisor drives the red LED, fail-closed. The OLED's render thread lives inside ingest, so when that process dies the display freezes showing plausible content and cannot report its own death.</span>
<span id="cb3-212"><a href="#cb3-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-213"><a href="#cb3-213" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Position <span class="pp">|</span> Colour <span class="pp">|</span> Name <span class="pp">|</span> Meaning <span class="pp">|</span></span>
<span id="cb3-214"><a href="#cb3-214" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb3-215"><a href="#cb3-215" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> blue <span class="pp">|</span> RF <span class="pp">|</span> RF trouble: foreign traffic or climbing CRC errors *(designed, not yet wired end-to-end)* <span class="pp">|</span></span>
<span id="cb3-216"><a href="#cb3-216" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> blue <span class="pp">|</span> CLOCK <span class="pp">|</span> Clock provenance: solid when restored from the RTC <span class="pp">|</span></span>
<span id="cb3-217"><a href="#cb3-217" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> red <span class="pp">|</span> NOT RECORDING <span class="pp">|</span> Solid when ingest is down or the clock gate refused; fast blink at low battery; slow pulse while shutting down <span class="pp">|</span></span>
<span id="cb3-218"><a href="#cb3-218" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> green <span class="pp">|</span> FLIGHT <span class="pp">|</span> Solid while a flight is open <span class="pp">|</span></span>
<span id="cb3-219"><a href="#cb3-219" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 5 <span class="pp">|</span> green <span class="pp">|</span> RX <span class="pp">|</span> Fast blink on fresh packets <span class="pp">|</span></span>
<span id="cb3-220"><a href="#cb3-220" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 6 <span class="pp">|</span> green <span class="pp">|</span> ALIVE <span class="pp">|</span> 1 Hz heartbeat, never solid, so a frozen supervisor shows as a stuck LED rather than a healthy one <span class="pp">|</span></span>
<span id="cb3-221"><a href="#cb3-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-222"><a href="#cb3-222" aria-hidden="true" tabindex="-1"></a>The operator rule that follows: when the two surfaces disagree, believe the LEDs. A dark RX LED under a plausible altitude on the OLED means ingest is dead and the screen is showing the past.</span>
<span id="cb3-223"><a href="#cb3-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-224"><a href="#cb3-224" aria-hidden="true" tabindex="-1"></a>Mapping those six positions was its own lesson. The harness is cross-wired, so physical order is not GPIO order. My first map, taken from watching a lamp sweep, was reversed in every position and stood wrong for three weeks. Lighting one LED at a time and counting its position was the only reliable method, and the map now lives as data in one Python module where a host test enforces that the GPIO table, the colour table and the lamp-test order agree.</span>
<span id="cb3-225"><a href="#cb3-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-226"><a href="#cb3-226" aria-hidden="true" tabindex="-1"></a><span class="fu">### The OLED</span></span>
<span id="cb3-227"><a href="#cb3-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-228"><a href="#cb3-228" aria-hidden="true" tabindex="-1"></a>The V1 box had no display. The first V2 OLED rendered straight off each decoded packet, which meant a quiet pad drew nothing and looked exactly like a dead box. The redesign moved rendering onto its own thread off a view-model snapshot, gave the pad an idle page, and put a spinning liveness glyph in the corner that proves the render thread is turning. The hero digits are hand-drawn 28-pixel bitmaps approved outdoors on the real panel before golden-image tests froze them, because a golden preserves whatever it was generated from, mistakes included.</span>
<span id="cb3-229"><a href="#cb3-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-230"><a href="#cb3-230" aria-hidden="true" tabindex="-1"></a>::: {layout-ncol=2}</span>
<span id="cb3-231"><a href="#cb3-231" aria-hidden="true" tabindex="-1"></a><span class="al">![Idle: no sled heard yet. Clock provenance shows here and only here, where the operator can cross-check it against the CLOCK LED.](https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/gs-oled-idle.png)</span></span>
<span id="cb3-232"><a href="#cb3-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-233"><a href="#cb3-233" aria-hidden="true" tabindex="-1"></a><span class="al">![Pad: the sled is up, baseline locking, altitude zeroed AGL.](https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/gs-oled-pad.png)</span></span>
<span id="cb3-234"><a href="#cb3-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-235"><a href="#cb3-235" aria-hidden="true" tabindex="-1"></a><span class="al">![Live ascent. Callsign in the header because Part 97 gives it a regulatory reason to be legible.](https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/gs-oled-live.png)</span></span>
<span id="cb3-236"><a href="#cb3-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-237"><a href="#cb3-237" aria-hidden="true" tabindex="-1"></a><span class="al">![Stale: silence during ascent is abnormal, so the state band says so and shows the age. Silence on the pad is normal and does not alarm.](https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/gs-oled-stale.png)</span></span>
<span id="cb3-238"><a href="#cb3-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-239"><a href="#cb3-239" aria-hidden="true" tabindex="-1"></a><span class="al">![Summary: holds the peak until the next flight opens, because this is what I read walking downrange with the box in hand.](https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/gs-oled-summary.png)</span></span>
<span id="cb3-240"><a href="#cb3-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-241"><a href="#cb3-241" aria-hidden="true" tabindex="-1"></a><span class="al">![Overflow policy: above 9,999 ft the hero switches units rather than shrinking or clipping, and truncates rather than rounds so it can never overstate altitude.](https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/gs-oled-overflow.png)</span></span>
<span id="cb3-242"><a href="#cb3-242" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-243"><a href="#cb3-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-244"><a href="#cb3-244" aria-hidden="true" tabindex="-1"></a>*Screens above are rendered by the ground station's own drawing code, not mocked up.*</span>
<span id="cb3-245"><a href="#cb3-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-246"><a href="#cb3-246" aria-hidden="true" tabindex="-1"></a><span class="al">![The OLED on the bench during the redesign, showing an earlier layout with the 1834 ft test value.](https://raw.githubusercontent.com/velezf/lora-rocket-telemetry/main/docs/site/images/v2-gs-oled-bench.jpg)</span></span>
<span id="cb3-247"><a href="#cb3-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-248"><a href="#cb3-248" aria-hidden="true" tabindex="-1"></a><span class="fu">### Dashboard and power</span></span>
<span id="cb3-249"><a href="#cb3-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-250"><a href="#cb3-250" aria-hidden="true" tabindex="-1"></a>A small Flask app inside the ingest service serves a phone-sized dashboard over the Pi's Wi-Fi, which joins my phone's hotspot at the range: per-vehicle flight badge and packet age, T+ since launch, AGL altitude, an RSSI sparkline and an events feed. It is a convenience path, not a data path. If the hotspot fails at the pad, capture, the panel and the OLED are all unaffected, which is why I was willing to close that item without ever observing an unattended cold-boot rejoin.</span>
<span id="cb3-251"><a href="#cb3-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-252"><a href="#cb3-252" aria-hidden="true" tabindex="-1"></a>The PiSugar governs power both ways. Auto-shutdown at 5 % after 30 s, and a double-tap on its button runs an orderly shutdown so the append-only session log closes with a clean final record; a raw power cut can truncate the last line. Wake-on-charge fires on the rising edge of external power being connected, not on power being present, so a box powered off with the charger plugged in stays off. That rising-edge semantic is the fact I most expect to have forgotten in six months, which is why it is written next to the config.</span>
<span id="cb3-253"><a href="#cb3-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-254"><a href="#cb3-254" aria-hidden="true" tabindex="-1"></a><span class="fu">## From session log to web page</span></span>
<span id="cb3-255"><a href="#cb3-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-256"><a href="#cb3-256" aria-hidden="true" tabindex="-1"></a>The flight archive is derived, never hand-edited. The ingest service writes one JSONL record per packet plus advisory events (flight open, flight close, service start and stop). A flights CLI segments a session into flights, derives each one, and exports a <span class="in">`flights.json`</span> summary plus a per-flight CSV of raw packets, which the Quarto archive page reads directly.</span>
<span id="cb3-257"><a href="#cb3-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-258"><a href="#cb3-258" aria-hidden="true" tabindex="-1"></a>The derivation that matters most is the **AGL baseline**. Raw barometric altitude at my bench reads about −85 ft. The baseline is a stability-gated trailing window over pad packets that locks the instant launch is detected, and both the baseline and the number of samples it used are stored with every flight so any AGL figure on the archive can be re-derived. The same pure function runs live on the ground station, on the handheld, and offline in the derivation, so the three never disagree about zero.</span>
<span id="cb3-259"><a href="#cb3-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-260"><a href="#cb3-260" aria-hidden="true" tabindex="-1"></a>The first record in the archive, 2026-07-08-F1, is a bench shake test: a hand-swung sled tripped launch detection and ran the whole pipeline end to end, with a 10 ft "peak" that is barometric noise. Its real over-the-air bytes are now a version-controlled golden fixture that every contract change has to reproduce exactly.</span>
<span id="cb3-261"><a href="#cb3-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-262"><a href="#cb3-262" aria-hidden="true" tabindex="-1"></a><span class="fu">## Flight day 2026-08-25</span></span>
<span id="cb3-263"><a href="#cb3-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-264"><a href="#cb3-264" aria-hidden="true" tabindex="-1"></a>Two Katana Jr flights on F15-6 motors at Izaak Walton Field, the first real 10 Hz flight records this system has produced. Both were on the archive page that evening.</span>
<span id="cb3-265"><a href="#cb3-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-266"><a href="#cb3-266" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Flight <span class="pp">|</span> Peak AGL <span class="pp">|</span> Packets <span class="pp">|</span> Loss <span class="pp">|</span> RSSI range <span class="pp">|</span> Max velocity <span class="pp">|</span> Max spin <span class="pp">|</span> Boost peak <span class="pp">|</span></span>
<span id="cb3-267"><a href="#cb3-267" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|---|---|---|---|</span></span>
<span id="cb3-268"><a href="#cb3-268" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2026-08-25-F1 <span class="pp">|</span> 859 ft <span class="pp">|</span> 3,222 <span class="pp">|</span> 0.31 % <span class="pp">|</span> −100 to −57 dBm <span class="pp">|</span> 201 ft/s <span class="pp">|</span> 1,177 dps <span class="pp">|</span> 10.4 g <span class="pp">|</span></span>
<span id="cb3-269"><a href="#cb3-269" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2026-08-25-F2 <span class="pp">|</span> 749 ft <span class="pp">|</span> 366 <span class="pp">|</span> 0.54 % <span class="pp">|</span> −97 to −69 dBm <span class="pp">|</span> — <span class="pp">|</span> 2,299 dps <span class="pp">|</span> — <span class="pp">|</span></span>
<span id="cb3-270"><a href="#cb3-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-271"><a href="#cb3-271" aria-hidden="true" tabindex="-1"></a>F1's record is long because the sled beaconed from the recovery grass for nine minutes before I reached it. F2 landed in an RF shadow at grass level and went quiet for 2.4 minutes after touchdown, which is the predicted recovery-beacon physics rather than flight loss. F2's spin peak sits at the gyro's full-scale limit, so the true rate is at least that.</span>
<span id="cb3-272"><a href="#cb3-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-273"><a href="#cb3-273" aria-hidden="true" tabindex="-1"></a>The flights found three bugs, all fixed the same evening. Wall-clock timestamps on the Pi invert by about 33 ms on a 20-second cadence, and the derivation was manufacturing packet loss from the reordering; it now honours arrival order. Publishing overwrote the archive instead of merging into it, which would have erased July's genesis record. And the publisher emitted a different schema than the page expected, so the new entries rendered as NaN until the page's schema was pinned as the contract.</span>
<span id="cb3-274"><a href="#cb3-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-275"><a href="#cb3-275" aria-hidden="true" tabindex="-1"></a>Three post-mortem items are still open with their evidence recorded and causes not chased: the box hard power-cut during pack-up at 95 % battery with no shutdown record, wake-on-charge did not fire on shore power at home, and the timestamp inversion itself is a Pi clock-discipline question whose durable fix is to record a monotonic time per packet.</span>
<span id="cb3-276"><a href="#cb3-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-277"><a href="#cb3-277" aria-hidden="true" tabindex="-1"></a><span class="fu">## What I learned</span></span>
<span id="cb3-278"><a href="#cb3-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-279"><a href="#cb3-279" aria-hidden="true" tabindex="-1"></a>**Write the contract first.** Everything downstream of ADR 0001 was cheap because both ends of the wire had a golden vector to fail against. When a newlib-nano printf quirk made every float tag encode empty on the real board, the end-to-end check caught it even though every host test passed.</span>
<span id="cb3-280"><a href="#cb3-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-281"><a href="#cb3-281" aria-hidden="true" tabindex="-1"></a>**Test logic on the host, glue on the hardware.** The firmware's detectors, encoder, conversions and schedule are pure C++ with no Arduino includes and run natively on the Mac. The ground driver, decoder, derivation, OLED spec and LED policy are pure Python with time and transport injected. The Pi and the Feather only ever run thin shells. This is what made the sample-rate and apogee-latency numbers measurable before anything flew.</span>
<span id="cb3-282"><a href="#cb3-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-283"><a href="#cb3-283" aria-hidden="true" tabindex="-1"></a>**State a fact once and cite it.** On one day I found the clock escape-hatch procedure in four places, the LED order contradicting itself within a single document, and a state-file path wrong in two places while the constant was right. The convention now is that literal values live at one authority and everything else links to it.</span>
<span id="cb3-284"><a href="#cb3-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-285"><a href="#cb3-285" aria-hidden="true" tabindex="-1"></a>**Ask whether a check could have failed.** A test pipeline whose exit status was <span class="in">`tail`</span>'s, a process check that matched its own command line, and a kill command that terminated the SSH session holding the pattern all happened in one day. Each reported success without verifying anything. The question to ask of any guard is not "did it pass" but "could this have failed".</span>
<span id="cb3-286"><a href="#cb3-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-287"><a href="#cb3-287" aria-hidden="true" tabindex="-1"></a>**A designed-but-inert signal is worse than an absent one.** The RF LED cannot fire today because nothing publishes the counters it reads. That is recorded in one canonical table in the repo, and nothing may be described as panel-covered until it comes off that list.</span>
<span id="cb3-288"><a href="#cb3-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-289"><a href="#cb3-289" aria-hidden="true" tabindex="-1"></a>**Don't stack two revolutions without a flight between them.** The Teensy 4.1 sled respin was decided in August, but sequenced firmly after the 10 Hz build flew on the Feather. A failure on an unflown RF rewrite and an unflown MCU port at the same time could not be attributed to either.</span>
<span id="cb3-290"><a href="#cb3-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-291"><a href="#cb3-291" aria-hidden="true" tabindex="-1"></a><span class="fu">## What's next</span></span>
<span id="cb3-292"><a href="#cb3-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-293"><a href="#cb3-293" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Epic 5, Teensy 4.1 sled respin.** Onboard Mahony fusion streaming a 10 Hz attitude, and the microSD flight recorder for spin spectra as a post-recovery product. The reasoning is in the link-budget section; the plan, port-cost audit and SD record design are written and waiting on hardware.</span>
<span id="cb3-294"><a href="#cb3-294" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Epic 7, the lander.** A KB2040 with a BME680 and APDS9960 as <span class="in">`SRC:2`</span>, separating at main and radioing its own atmosphere and light data home on the same grammar. The tag names are already reserved.</span>
<span id="cb3-295"><a href="#cb3-295" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Open hardening.** Wire the RF LED and the write-failure leg of the red LED; record monotonic time per packet; chase the hard power-cut.</span>
<span id="cb3-296"><a href="#cb3-296" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**The [handheld](apogee-handheld.qmd) at a real launch.** Family-tested on the bench, not yet flown.</span>
<span id="cb3-297"><a href="#cb3-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-298"><a href="#cb3-298" aria-hidden="true" tabindex="-1"></a><span class="fu">## Links</span></span>
<span id="cb3-299"><a href="#cb3-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-300"><a href="#cb3-300" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">GitHub repository</span><span class="co">](https://github.com/velezf/lora-rocket-telemetry)</span></span>
<span id="cb3-301"><a href="#cb3-301" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Flight archive</span><span class="co">](lora-flights.qmd)</span> and <span class="co">[</span><span class="ot">V1 write-up</span><span class="co">](lora-radiorocket.qmd)</span></span>
<span id="cb3-302"><a href="#cb3-302" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Kids' handheld</span><span class="co">](apogee-handheld.qmd)</span></span>
<span id="cb3-303"><a href="#cb3-303" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Decision records: <span class="co">[</span><span class="ot">0001 packet format</span><span class="co">](https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/adr/0001-packet-format-v1.md)</span> · <span class="co">[</span><span class="ot">0002 native RX driver</span><span class="co">](https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/adr/0002-ground-rx-driver-spidev.md)</span> · <span class="co">[</span><span class="ot">0003 clock integrity</span><span class="co">](https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/adr/0003-rtc-boot-restore-clock-gate.md)</span> · <span class="co">[</span><span class="ot">0005 rate and RF</span><span class="co">](https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/adr/0005-telemetry-rate-and-rf-configuration.md)</span></span>
<span id="cb3-304"><a href="#cb3-304" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Sled firmware</span><span class="co">](https://github.com/velezf/lora-rocket-telemetry/tree/main/firmware)</span> · <span class="co">[</span><span class="ot">Ground service</span><span class="co">](https://github.com/velezf/lora-rocket-telemetry/tree/main/ground)</span> · <span class="co">[</span><span class="ot">Field checklist</span><span class="co">](https://github.com/velezf/lora-rocket-telemetry/blob/main/docs/field-checklist.md)</span></span>
<span id="cb3-305"><a href="#cb3-305" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Original concept: <span class="co">[</span><span class="ot">N3VEM's RadioRocketV2</span><span class="co">](https://github.com/N3VEM/RadioRocketV2)</span></span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2025 Francisco Velez</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/velezf">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>